# Generated by Django 5.2.3 on 2025-08-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tarefa_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='atraso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluido'), ('Não Concluído', 'N Concluido')], default='Não Concluído'),
        ),
    ]
